### ISSUE TITLE
what was the intended goal?

### ISSUE THREAD

**Issue by Noitidart** [hlandau/nczilla#1]
What was the intended goal for this addon? How come halted?

**Comment by hlandau** [comment]
This was some early experimentation with adapting Firefox for use with Namecoin, including TLS validation based on trust roots encoded in the Namecoin key-value store.

(Nowadays @JeremyRand would know more about the current state of affairs as regards Firefox support.)

I'm curious, what drew your interest to this repository?

**Comment by Noitidart** [comment]
Thanks for that quick reply! I was unstarring the starred repos on my profile and this was one of them.
